stages:
    instantiate-project:
        deps: 
            - Manifest.toml
        cmd: julia --project --startup-file=no -e'using Pkg; Pkg.instantiate(); Pkg.precompile()'
    make-estimands:
        cmd: julia --project --startup-file=no scripts/make_variants_and_estimands_files.jl
        deps: 
            - scripts/make_variants_and_estimands_files.jl
        outs:
            - assets/estimands
            - assets/variants.txt
    simulation:
        wdir: geneatlas_simulation
        cmd: nextflow run ../main.nf -resume -with-trace -profile eddie -N s2042526@ed.ac.uk
        deps:
            - ../assets/estimands
            - nextflow.config
        outs:
            - results/permutation_simulation_results.hdf5
            - results/gene_atlas_simulation_results.hdf5