stages:
    discovery:
        cmd: nextflow run https://github.com/TARGENE/targene-pipeline -r 2ca5a9272dc84b606092ffac621b807758cbc112 -entry MAKE_DATASET -profile eddie -resume -with-trace -with-report -N s2042526@ed.ac.uk
        deps:
            - assets
            - nextflow.config
            - /exports/igmm/eddie/UK-BioBank-53116/imputed/ukb_snp_qc.txt
            - /exports/igmm/eddie/UK-BioBank-53116/phenotypes/ukb45981.enc_ukb
            - /exports/igmm/eddie/UK-BioBank-53116/phenotypes/encoding.ukb
            - /exports/igmm/eddie/UK-BioBank-53116/imputed/ukb_53116_chr1.bgen
            - /exports/igmm/eddie/UK-BioBank-53116/genotypes/ukb_53116_chr1.bed